In [5]:
import numpy as np

In [ ]:
np.__version__

In [6]:
lst = [1,2,3,4,4,5,5,7,8]
print("List : ",lst)
print(type(lst))
print("Converting to array")
arr = np.array(lst)
print("array : ",arr)
print(type(arr))

List :  [1, 2, 3, 4, 4, 5, 5, 7, 8]
<class 'list'>
Converting to array
array :  [1 2 3 4 4 5 5 7 8]
<class 'numpy.ndarray'>


In [8]:
arr = np.array([1,2,3,4])

In [10]:
arr = np.array(list(range(1,10)))

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [13]:
arr= np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr = np.ones(20)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
arr = np.zeros((5,10))   # yaha pe double parenthesis aayege
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
arr = np.arange(60)
# print(arr)
# 1 d array converted to a 2d array
arr = arr.reshape(12,5) # the multplication should be eqal to size
# print(arr)

In [21]:
# array attributes
print("datatype of array :-",arr.dtype)
print(arr.size)
print(arr.shape)
print(arr.ndim)

datatype of array :- int32
60
(12, 5)
2


In [25]:
arr[1]

array([5, 6, 7, 8, 9])

In [ ]:
arr[0:5,0:1] # pahla slicing rows k liye second column k liye

array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

In [27]:
arr[11][4]

59

In [28]:
arr[11,4]

59

In [29]:
arr[-1,-1]

59

In [30]:
arr[11,-1]

59

In [31]:
arr[-1,4]

59

In [32]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [33]:
arr[4:6,2:4]

array([[22, 23],
       [27, 28]])